# ***************************************************************************************
#
#      Name :      mda14.py
#      Author :    bmarty <bmarty@mailo.com>
#      Purpose :   Build font_8x14.h (glyphs $20-$7F, 8x14, MSB first) from the IBM MDA
#                  character generator, as reproduced by the Ultimate Oldschool PC Font
#                  Pack v2.2 (VileR, int10h.org), file Bm437_IBM_MDA.otb, CC BY-SA 4.0.
#                  See assets/Bm437_IBM_MDA.LICENSE.txt.
#
#                  The MDA (and therefore Hercules) character generator draws in a 9x14
#                  cell : the glyphs use columns 0-7 and the 9th column is blank, except
#                  for the line-drawing characters $C0-$DF where the 8th column is
#                  replicated. Only $20-$7F is exported, so no glyph is truncated.
#
#      Usage :     python3 mda14.py [source.otb] [dest.h]
#
# ***************************************************************************************
import sys
from PIL import Image, ImageDraw, ImageFont

src = sys.argv[1] if len(sys.argv) > 1 else "assets/Bm437_IBM_MDA.otb"
dst = sys.argv[2] if len(sys.argv) > 2 else "../common/include/interface/font_8x14.h"

PAD, CELL_X, CELL_Y, W, H = 2, 9, 14, 8, 14
font = ImageFont.truetype(src, 16)  											# native strike of the bitmap font


def glyph(code):
    """Render one CP437 code point and return its 14 rows of 8 pixels, MSB first."""
    image = Image.new("1", (CELL_X + 2 * PAD, CELL_Y + 2 * PAD + 6), 0)
    ImageDraw.Draw(image).text((PAD, PAD), bytes([code]).decode("cp437"), font=font, fill=1)
    pixel = image.load()
    return [sum(1 << (7 - x) for x in range(W) if pixel[PAD + x, PAD + 2 + y]) for y in range(CELL_Y)]


out = ["// Generated by firmware/scripts/mda14.py from Bm437_IBM_MDA.otb (IBM MDA 8x14, $20-$7F),",
       "// Ultimate Oldschool PC Font Pack v2.2 by VileR (int10h.org), CC BY-SA 4.0. Do not edit.",
       "#pragma once", "#include <cstdint>", "", "const uint8_t font_8x14[] = {"]
for code in range(0x20, 0x80):
    label = chr(code) if 0x20 < code < 0x7F and code != 0x5C else ""
    out.append("    " + ",".join("0x%02x" % b for b in glyph(code)) + ", // $%02x %s" % (code, label))
out += ["};", ""]
open(dst, "w").write("\n".join(out))
print("font_8x14.h : 96 glyphes x %d lignes (IBM MDA)" % CELL_Y)
