# ***************************************************************************************
#
#      Name :      vga14.py
#      Author :    bmarty <bmarty@mailo.com>
#      Purpose :   Build font_8x14.h (glyphs $20-$7F, 8x14, MSB first) from the Linux
#                  console font Lat15-VGA14.psf.gz (console-setup : "All console fonts
#                  are public domain by nature"). Used by the Hercules text mode (F-52),
#                  drawn in a 9x14 cell with a blank 9th column.
#
# ***************************************************************************************
import gzip, struct, sys

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-VGA14.psf.gz"
dst = sys.argv[2] if len(sys.argv) > 2 else "../common/include/interface/font_8x14.h"
data = gzip.open(src).read()
assert data[0:2] == b"\x36\x04", "PSF1 attendu"
mode, height = data[2], data[3]
count = 512 if mode & 1 else 256
glyphs = [data[4 + i * height:4 + (i + 1) * height] for i in range(count)]
# PSF1 unicode table : for each glyph, UCS-2 codes terminated by 0xFFFF
cp_to_glyph = {}
if mode & 2:
    p = 4 + count * height
    for g in range(count):
        while True:
            cp = struct.unpack_from("<H", data, p)[0]; p += 2
            if cp == 0xFFFF: break
            if cp == 0xFFFE: continue
            cp_to_glyph.setdefault(cp, g)
else:
    cp_to_glyph = {i: i for i in range(count)}
out = ["// Generated by firmware/scripts/vga14.py from Lat15-VGA14.psf (8x14, $20-$7F), do not edit.",
       "#pragma once", "#include <cstdint>", "", "const uint8_t font_8x14[] = {"]
for ch in range(0x20, 0x80):
    g = glyphs[cp_to_glyph.get(ch, cp_to_glyph[0x3F])]
    out.append("    " + ",".join("0x%02x" % b for b in g) + ", // $%02x %s" % (ch, chr(ch) if 0x20 < ch < 0x7F and ch != 0x5C else ""))
out += ["};", ""]
open(dst, "w").write("\n".join(out))
print("font_8x14.h :", 96, "glyphes x", height)
